language: rust
rust: stable
cache: cargo    # cache Cargo dependency build objects

os: linux

# Databases and Services - https://docs.travis-ci.com/user/database-setup/
services: postgresql

# Job Lifecycle - https://docs.travis-ci.com/user/job-lifecycle
#   2 main parts:
#     1. install: install any dependencies required
#     2. script: run the build script

install:
  - function not_installed() { command -v "$1" >/dev/null 2>&1 && return 1 || return 0; }
  - if not_installed diesel; then cargo install diesel_cli; fi

before_script:
  - source .env
  - diesel database setup --database-url="$TEST_DATABASE_URL"

script:
  - cargo test
  - cargo doc

before_deploy:
  - mkdir public
  - cp -r target/doc public/

# GitHub Pages Deployment - https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  keep_history: true
  on:
    branch: master
