language: rust

rust:
  - stable

os:
  - linux

services:
  - postgresql

install:
  - cargo install diesel_cli

before_script:
  - source .env
  - diesel database setup --database-url="$TEST_DATABASE_URL"

script:
  - cargo test

cache: cargo    # cache Cargo packages
